
package Presentacion.Controller;

public enum ContextEnum { 
	
	ALTACLIENTE, BAJACLIENTE, MODIFICARCLIENTE, MOSTRARCLIENTE, MOSTRARCLIENTEPARAMODIFICAR, LISTARCLIENTES, LISTARCLIENTESNORMAL, LISTARCLIENTESVIP,
	CERRARCOMPRA, MOSTRARCOMPRA, LISTARCOMPRAS, MOSTRARCOMPRAENDETALLE, LISTARCOMPRASPORCLIENTE, LISTARCOMPRASPORPASE, DEVOLVERCOMPRA, CALCULARTOTALCOMPRASPORPELICULA, VERRESUMENDECOMPRA,
	ALTAPASE, BAJAPASE, MODIFICARPASE, MOSTRARPASE, MOSTRARPASEPARAMODIFICAR, LISTARPASES, LISTARPASESPORSALA, LISTARPASESPORPELICULA, LISTARPASESPORCOMPRA,
	ALTAPELICULA, BAJAPELICULA, MODIFICARPELICULA, MOSTRARPELICULA, MOSTRARPELICULAPARAMODIFICAR, LISTARPELICULAS, LISTARPELICULASPORPRODUCTORA, ANADIRPRODUCTORA, QUITARPRODUCTORA, 
	ALTAPRODUCTORA,BAJAPRODUCTORA, MODIFICARPRODUCTORA, MOSTRARPRODUCTORA, MOSTRARPRODUCTORAPARAMODIFICAR, LISTARPRODUCTORAS, LISTARPRODUCTORASPORPELICULA, CALCULARPRODUCTORAMASINGRESOS,
	ALTASALA, BAJASALA, MODIFICARSALA, MOSTRARSALA, MOSTRARSALAPARAMODIFICAR, LISTARSALAS, LISTARSALASESTANDAR, LISTARSALASESPECIALES
	
}